# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: aws
  #vmImage: ubuntu-latest

steps:
    - task: AWSCLI@1
      displayName: "Running aws-cli get-caller-identity"
      inputs:
        awsCredentials: "AWS"
        regionName: 'us-east-1'
        awsCommand: 'sts'
        awsSubCommand: 'get-caller-identity'