apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.application.name}}
  labels:
    app: {{.Values.application.name}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.application.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.application.name}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          resources: {}
          ports:
            - containerPort: 3080
          volumeMounts:
            - name: index-file
              mountPath: /www
      volumes:
      - name: index-file
        configMap:
          name: index-html-configmap
status: {}